name: "Upload new system"
description: "Upload a system exported by abbrv."
title: "[SYSTEM-UPLOAD] - <system name>"
labels: ["system-upload"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        ## Instructions
        Please upload your JSON files below and provide any additional details needed for processing.

  - type: input
    id: description
    attributes:
      label: "Description"
      description: "Provide a brief description of the JSON files and their purpose."
      placeholder: "E.g., Dataset for material science analysis."
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Any specific requirements or context for these files?"
      placeholder: "E.g., Formatting guidelines, expected outputs."

  - type: file-upload
    id: files
    attributes:
      label: "JSON Files"
      description: "Drag and drop or select up to four JSON files."
      multiple: true
      filetypes: ["json"]
    validations:
      required: true