name: "Upload new system"
description: "Upload a system exported by abbrv."
title: "[SYSTEM-UPLOAD] - <system name>"
labels: ["system upload"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        ## Instructions
        1. Submit this issue first.
        2. Once the issue is created, **add a comment** with four JSON files attached.
        3. Include the word **upload** in the comment so that the validation process starts.

  - type: input
    id: your-name
    attributes:
      label: "Your name"
    validations:
      required: true

  - type: input
    id: system-name
    attributes:
      label: "System name"
    validations:
      required: true

  - type: input
    id: system-description
    attributes:
      label: "System description"
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: "System files"
      description: "Use the 'add file' option to add [glyphs, rules, modes, phrases].json files."
    validations:
      required: true