name: "Upload new system"
description: "Upload a system exported by abbrv."
title: "[SYSTEM-UPLOAD] - <system name>"
labels: ["system upload"]
assignees:
  - ""
body:
  - type: input
    id: your-name
    attributes:
      label: "Your name"
      description: "Your name as you would like it to appear in abbrv when crediting your contributions."
    validations:
      required: true

  - type: input
    id: system-name
    attributes:
      label: "System name"
      description: "The name of the shorthand system you are uploading."
    validations:
      required: true

  - type: input
    id: system-description
    attributes:
      label: "System description"
      description: "A brief description of the shorthand system you are uploading."
    validations:
      required: true
